import { lazy, Suspense, useEffect, useState } from 'react';
import { Home, MessageCircle, Link, Settings as SettingsIcon, ClipboardList, Play, CircleHelp, ChevronRight, X } from 'lucide-react';
import { api, bootstrap, type Settings, type Status, type Job } from './api';
import { Jobs } from './components';
const SettingsPage=lazy(()=>import('./SettingsPage'));
const PlatformsPage=lazy(()=>import('./PlatformsPage'));
const ChatPage=lazy(()=>import('./ChatPage'));
type Page='總覽'|'本機試聊'|'平台串接'|'設定'|'工作紀錄'|'使用指南';
const nav=[['總覽',Home],['本機試聊',MessageCircle],['平台串接',Link],['設定',SettingsIcon],['工作紀錄',ClipboardList]] as const;
export default function App(){
 const [page,setPage]=useState<Page>('總覽'),[settings,setSettings]=useState<Settings>(),[status,setStatus]=useState<Status>(),[jobs,setJobs]=useState<Job[]>([]),[notice,setNotice]=useState(''),[offline,setOffline]=useState(false);
 useEffect(()=>{let active=true;bootstrap().then(d=>{if(active){setSettings(d.settings);setStatus(d.status)}}).catch(e=>setNotice(e.message));let timer:ReturnType<typeof setTimeout>;let busy=false;// 有工作分析中時加快更新，讓工具進度即時顯示
async function poll(){try{const [s,j]=await Promise.all([api<Status>('/status'),api<Job[]>('/jobs')]);if(active){setStatus(s);setJobs(j);setOffline(false)}busy=j.some(x=>x.status==='running')}catch{if(active)setOffline(true)}if(active)timer=setTimeout(poll,busy?800:2000)}void poll();return()=>{active=false;clearTimeout(timer)}},[]);
 return <div className="shell"><aside><div className="brand">Stock Bot<small>個股分析機器人</small></div><nav>{nav.map(([name,Icon])=><button className={page===name?'active':''} key={name} onClick={()=>setPage(name)}><Icon size={21}/>{name}</button>)}</nav><div className="local-status"><Play size={20}/><div>本機執行<small><i className={offline?'offline':''}/>{offline?'連線中斷':'控制台已就緒'}</small></div></div></aside><div className="workspace"><header><strong>{page}</strong><button className="help" onClick={()=>setPage('使用指南')}><CircleHelp size={20}/>使用指南</button></header><main>{offline&&<p className="error">無法連到本機服務，請確認啟動視窗仍在執行。</p>}{notice&&<div className="notice" role="status"><span>{notice}</span><button aria-label="關閉通知" onClick={()=>setNotice('')}><X size={18}/></button></div>}{settings&&status?<Suspense fallback={<p>載入中…</p>}>
 {page==='總覽'&&<><h1>開始你的股票分析對話</h1><p className="intro">先設定 AI，再選擇你習慣的聊天平台。</p><div className="onboarding">{([['設定 OpenAI','填入金鑰並完成測試','設定'],['本機試聊','先在電腦上與 AI 對話','本機試聊'],['串接聊天平台','選擇並設定 Telegram 或 LINE','平台串接']] as const).map(([title,desc,dest],i)=><button key={title} onClick={()=>setPage(dest)}><b>0{i+1}</b><span><strong>{title}</strong><small>{desc}</small></span>{i<2&&<ChevronRight/>}</button>)}</div><h2>聊天平台</h2><div className="platform-grid">{(['Telegram','LINE'] as const).map(name=><section className="platform-card" key={name}><div className="platform-summary"><div className={`platform-mark ${name.toLowerCase()}`}>{name==='LINE'?'LINE':<SendIcon/>}</div><div><div className="section-heading"><h3>{name}</h3><span className="badge">{name==='LINE'?status.line:status.telegram}</span></div><p>{name==='LINE'?'透過 ngrok 接收訊息，讓你的 LINE 可以與 Stock Bot 對話。':'不需要公開網址，使用 Bot Token 即可串接。'}</p></div></div><footer><button onClick={()=>setPage('平台串接')}>設定 {name}</button></footer></section>)}</div><h2>最近工作</h2><Jobs jobs={jobs.slice(0,5)} go={()=>setPage('本機試聊')}/></>}
 {page==='設定'&&<SettingsPage settings={settings} updated={setSettings} notify={setNotice}/>}
 {page==='平台串接'&&<PlatformsPage settings={settings} status={status} updated={setSettings} notify={setNotice}/>}
 {page==='本機試聊'&&<ChatPage jobs={jobs} notify={setNotice}/>}
 {page==='工作紀錄'&&<><p className="intro">最近 100 筆工作。展開可查看結果或失敗原因。</p><Jobs jobs={jobs} go={()=>setPage('本機試聊')}/></>}
 {page==='使用指南'&&<><h1>使用指南</h1><p className="intro">延續第五章的操作方式，從本機對話開始。</p><section className="form-panel guide"><h2>第一次使用</h2><ol><li>在「設定」填入 OpenAI API Key 與模型 ID，儲存後測試連線。</li><li>到「本機試聊」詢問股票，確認模型與資料來源可用。</li><li>到「平台串接」選擇 LINE 或 Telegram，依畫面步驟完成。</li></ol><h2>LINE 要多做什麼？</h2><p>建立官方帳號、設定 Messaging API，再啟用 ngrok。將完整 Webhook 網址貼到 LINE Developers，按 Verify 並開啟 Use webhook。設定控制台不會透過此通道公開。</p><h2>為什麼收到兩則訊息？</h2><p>LINE 先回覆處理中通知，分析完成後再推播結果。推播會使用 LINE 訊息額度；OpenAI 與 ngrok 另有各自用量。</p><h2>日常啟動與關閉</h2><p>Windows 雙擊 start.bat；macOS 在專案資料夾執行 uv run --locked stock-bot。保持終端機開啟、電腦連網；Ctrl+C 可停止。關閉瀏覽器不會停止機器人。</p><h2>資料與金鑰</h2><p>對話與設定保存在使用者目錄的 .stock-bot；金鑰優先使用系統憑證庫。若憑證庫不可用，可用環境變數設定，詳見專案 README。送出的問題與查到的資料會傳给 OpenAI 分析。</p><h2>遇到問題</h2><ul><li>未收到訊息：確認平台已啟用，查看最近接收時間。</li><li>LINE 驗證失敗：確認 ngrok 已連線、完整路徑及 Channel secret。</li><li>Telegram 衝突：停止其他接收程序，必要時解除舊 Webhook。</li><li>資料來源失敗：縮小問題或稍後重試，不會以假資料補上。</li><li>待確認：傳送途中斷線，先查看聊天軟體，避免重複提問。</li></ul><p>更完整的安裝與架構說明，請閱讀專案 README.md 與 docs 資料夾。</p></section></>}
 </Suspense>:<p>正在連接本機控制台…</p>}</main></div></div>;
}
function SendIcon(){return <svg viewBox="0 0 24 24" fill="currentColor" width="32" height="32" aria-hidden="true"><path d="m21 3-4 18-6-5-3 3 1-6 9-7-12 6-4-2L21 3Z"/></svg>}
